// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using LiveLarson.Enums;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine;

namespace DataTables
{
    [Serializable]
    public class SessionInfo
    {
        public int ParticipantID;
        public bool IsAutoDrive;
        public string Session1;
        public string Session2;
        public string Session3;
        public string Session4;
        public string Session5;
        public string Session6;
        public string Session7;
        public string Session8;
        public string NoiseMode;
    }

}

