// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using LiveLarson.Enums;
using UnityEngine;

namespace DataTables
{
    [Serializable]
    public class Stimuli
    {
        public int ID;
        public string Contrast;
        public string A;
        public string B;
    }

}

